volumes:
  data:
  export:
networks:
  idm_network:

services:
  postgres-db:
    image: docker.io/postgres:17-alpine
    container_name: idm-postgres-server
    hostname: postgres-db
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=idm_db
    volumes:
      - data:/var/lib/postgresql/data
      - export:/export
    networks:
      - idm_network